package me.erotoro.treechopper.replant;

public enum ReplantResultType {
    PLANTED,
    FEATURE_DISABLED,
    WORLD_DISABLED,
    ONLY_NATURAL_ENABLED,
    UNSUPPORTED_TREE_TYPE,
    MEGA_DISABLED,
    MISSING_PLANTING_LOCATION,
    INVALID_PLANTING_LOCATION,
    PROTECTION_DENIED,
    PLAYER_UNAVAILABLE,
    MISSING_SAPLING,
    SAPLING_CONSUME_FAILED
}
